### ISSUE TITLE
Contact Point ontology

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/CPOV#16]
During the Core Vocs webinar dd. 2021-04-23, several participants expressed their interest in creating an upper level ontology for defining contact points.

**Comment by paulakeen** [comment]
In ePO, we saw that Contact Points are tightly related to the [reification] pattern Agent-Role, since at least for Publica Administrations one Agent may play different roles, each role with a different contact point, depending on the situations. Hence, the reification putting everything together links Agent to Role to Contact Point to “Thing” (the object of the action performed by the Agent with a specific Role).

**Comment by aidig** [comment]
Question: Schema.org regards 'postal address' a specialization of 'contact point' (https://schema.org/PostalAddress). Would this be introduced too when schema:ContactPoint is replicated in the SEMIC namespace?

**Comment by EmidioStani** [comment]
Discussion will continue on https://github.com/SEMICeu/Core-Person-Vocabulary/issues/36
