### ISSUE TITLE
CPSV-AP / CPOV consistency: specialOpeningHoursSpecification

### ISSUE THREAD

**Issue by NathanGhesq** [SEMICeu/CPOV#23]
In CPSV-AP 3.0.0, the URI of the property AvailabilityRestriction has been changed (https://github.com/catalogue-of-services-isa/CPSV-AP/issues/70) from cv:openingHoursSpecification to cv:specialOpeningHoursSpeciciation to reflect the exceptional case in which a Channel (and also a Contactpoint) is open.

The AvailabilityRestriction of Contactpoint should have the same URI.

**Comment by EmidioStani** [comment]
Proposal to change the URI from cv:openingHoursSpecification to cv:specialOpeningHoursSpeciciation

However the proposal, in conjonction with Core Public Event, is also to change the range of the property from OpeningHoursSpecification to TemporalEntity.

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to:
- Fix the URI in compliance with CPSV-AP to cv:specialOpeningHoursSpecification.
- Make openingHours a relation instead of a property.
- Replace the Class OpeningHoursSpecification with time: TemporalEntity, this will be in alignment with Core Public Event.

**Comment by pebran** [comment]
Where exactly can I see that the issue has been completed? I do not see it on the UML diagram.
