### ISSUE TITLE
AdminTerritorialUnits class and its role

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/CPOV#7]
AdminTerritorialUnits class should be singular as the name of all the classes.

In addition, what does it mean here? Is this a Location in the sense of dct:Location defined in CLV? If so let’s use it otherwise it may also be a problem using the geometry property that is linked to dct:Location in CLV unless we say that AdminTerritorialUnit is equivalentClass  dct:Location. BTW: this class seems modelling the concepts of AdminUnit1 and AdminUnit2 of the Address class defined in CLV.

I believe these spatial concepts need to be clarified across all the EU core vocs.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, there was an argument that Administrative Territorial Units should not be reduced to a spatial relationship, since two types of locations can be distinguished for a Public Organisation: the address (territorial organisation) and the jurisdiction (depending on how the competences are distributed among the different administrations of a country). Furthermore, it was mentioned that NUTS does not match exactly with the jurisdictional units in some countries.

The editorial team therefore proposes
- to change the _spatial_ relationship with the _jurisdiction_ relationship;
- to not conflate NUTS with Administrative Territorial Units (as NUTS is for statistical and not jurisdictional purposes);
- to delete the relationship between AdministrativeTerritorialUnits and the Geometry class.

**Comment by dimi-schepers** [comment]
In addition, the class name should be singular.

**Comment by EmidioStani** [comment]
During the webinar of 09/11/2021 it has been agreed that:

- the class name should be singular.
- to change the spatial relationship with the jurisdiction relationship;
- to not conflate NUTS with Administrative Territorial Units (as NUTS is for statistical and not jurisdictional purposes);
- to delete the relationship between AdministrativeTerritorialUnits and the Geometry class.
